/*
##
##	Enhancer for YouTube™ | Firefox Add-on
##	======================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Being an AMO Editor doesn't give you that right!
##	Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
(function(a){if(!window.EnhancerForYouTube){var Ha=function(c){q&&"yt-navigate-start"===c.type&&(a.location.href=c.detail.url);clearInterval(sa);clearInterval(S);L=Z=aa=D=!1;x&&(x.style.display="none",y.style.display="none",E&&(clearInterval(ba),k.querySelector("i.loop").parentNode.classList.remove("active"),E.slider("destroy"),E[0].style.display="none"));a.body.classList.remove("enhancer-for-youtube-pinned-player");try{if("yt-history-load"===c.type||"yt-navigate-start"===c.type&&"watch"!==c.detail.pageType)ia(),
G("default");d.classList.remove("ads-removed")}catch(h){}},Ia=function(a){var e;"undefined"===typeof a&&(e=JSON.parse(localStorage.getItem("enhancer-for-youtube")||'{"customtheme":""}'));localStorage.setItem("enhancer-for-youtube",JSON.stringify({customtheme:e?e.customtheme:a,theme:c.theme.replace("-polymer.css",".css"),polymer:!0}))},ua=function(c){try{var e=c||a.querySelector("ytd-compact-autoplay-renderer");if(e){var b=e.querySelector("#head > paper-toggle-button#toggle"),d=e.querySelector("#head > paper-toggle-button#improved-toggle");
(b.checked||b.active)&&b.click();(d.checked||d.active)&&d.click();ta=!0;t()}else setTimeout(ua,2E3)}catch(w){}},va=function(){if(k){for(var a=k.querySelectorAll("li"),h=c.toolbarbuttons.split(","),b=a.length-1;0<=b;b--)a[b].classList[-1<h.indexOf(a[b].dataset.name)?"remove":"add"]("hidden");k.querySelector('li[data-name="message"]').classList[c.message?"remove":"add"]("hidden");""!==c.toolbarbuttons||c.message?(x.classList.remove("hidden"),Ja()):x.classList.add("hidden")}},eb=function(){ja();if(0===
E[0].children.length){var a=r;E.slider({animate:"slow",range:!0,min:0,max:J,values:[r,u],start:function(c,b){a=r},slide:function(a,b){r=b.values[0];u=b.values[1];ja()},stop:function(c,b){r===J?(r=J-1,wa(),ja()):u===r&&(u=r+1,wa(),ja());a!==r&&d.seekTo(r)}})}else wa();E.show();x.classList.add("extended")},wa=function(){E.slider("values",[r,u])},ja=function(){Ka[0].textContent=xa(r)+" / "+xa(u)},La=function(c){if(c.classList.contains("active"))clearInterval(ba),c.classList.remove("active"),E.hide(),
x.classList.remove("extended"),g&&(g.loop=!1);else{c.classList.add("active");0===$("#enhancer-for-youtube-slider",k).length&&(E=$("<div />").attr("id","enhancer-for-youtube-slider").appendTo(k),Ka=$("<div />").addClass("start-end").appendTo(k));J=r=u=!1;var e=0,b=0<a.location.href.indexOf("list=");ba=setInterval(function(){try{d&&"function"===typeof d.getPlayerState?J?!b&&d.getCurrentTime()>=u?d.seekTo(r):b||0!==d.getPlayerState()?(b&&!g&&J===u&&2>J-d.getCurrentTime()||b&&J!==u&&d.getCurrentTime()>=
u)&&d.seekTo(r):d.playVideo():(J=u=parseInt(d.getDuration(),10),r=0,"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&(r=ytplayer.config.args.start?parseInt(ytplayer.config.args.start,10):0,u=ytplayer.config.args.end?parseInt(ytplayer.config.args.end,10):u),g&&(g.loop=!0),e=0,eb()):(e++,O())}catch(f){15<e&&clearInterval(ba),d=!1,g&&(g.loop=!1)}},1E3)}},xa=function(a){a=Number(a);var c=Math.floor(a/3600),b=Math.floor(a%3600/60);a=Math.floor(a%3600%60);return(0<c?c+":":"")+(0<b?
(0<c&&10>b?"0":"")+b+":":"0:")+(10>a?"0":"")+a},ya=function(){a.body.classList.contains("no-scroll")||A&&A.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar")||a.documentElement.hasAttribute("fullscreen")||(a.body.classList.remove("enhancer-for-youtube-pinned-player"),a.body.classList.contains("viewport")&&(a.body.classList.remove("viewport"),a.body.classList.add("_viewport_")),window.scrollTo(0,0),a.body.classList.add("enhancer-for-youtube-cinema-mode"),parseInt(16/9*(a.documentElement.clientHeight-
56-29),10)>a.documentElement.clientWidth&&a.body.classList.add("_overflow-auto"),c.cinemamodewideplayer&&!a.body.classList.contains("enhancer-for-youtube-wide-player")&&G("large"),0<=c.autofocusevents.indexOf("cinema")&&t(),k&&k.querySelector("i.cinema").parentNode.classList.add("active"))},ia=function(){a.body.classList.contains("no-scroll")||A&&A.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar")||a.documentElement.hasAttribute("fullscreen")||(a.body.classList.remove("enhancer-for-youtube-cinema-mode",
"_overflow-auto"),!c.wideplayer&&c.cinemamodewideplayer?G("default"):a.body.classList.contains("_viewport_")&&(a.body.classList.remove("_viewport_"),G("large")),0<=c.autofocusevents.indexOf("cinema")&&t(),k&&k.querySelector("i.cinema").parentNode.classList.remove("active"))},Ma=function(a){if(c.controlvolumemousebutton&&ka)return a.stopPropagation(),a.preventDefault(),la=ka=!1},Na=function(a){2===a.button&&c.controlvolumemousebutton&&(la=!0)},T=function(){var a=[c.quality1,c.quality2,c.quality3,c.quality4],
h=setInterval(function(){try{if(d&&"function"===typeof d.getPlayerState||("video"===F?O():za()),-1!==d.getPlayerState()){for(var c=0,e=!1,g,k=d.getAvailableQualityLevels();c<a.length&&!e;c++)for(var p in k)if(a[c]===k[p]){e=a[c];break}g=e?e:"auto";g!==d.getPlaybackQuality()?H||(H=!0,d.hasAttribute("flashvars")?(d.pauseVideo(),d.setPlaybackQuality(g),d.playVideo()):d.setPlaybackQuality(g)):g===d.getPlaybackQuality()&&(H=!0,clearInterval(h),clearTimeout(b))}}catch(ma){d=!1}},500),b=setTimeout(function(){clearInterval(h)},
3E4)},fa=function(e){d||O();if(d&&d.hasAttribute("flashvars")){clearInterval(ba);clearInterval(S);k&&E&&(k.querySelector("i.loop").parentNode.classList.remove("active"),E.slider("destroy"),E[0].style.display="none");var h="ad_module ad2_module ad3_module ad_channel_code_instream ad_channel_code_overlay ad_device ad_eurl ad_flags ad_host ad_host_tier ad_logging_flag ad_preroll ad_slots ad_tag ad_type ad_video_pub_id adsense_video_doc_id advideo aftv afv afv_ad_tag afv_ad_tag_restricted_to_instream afv_invideo_ad_tag afv_inslate_ad_tag afv_instream_max afv_video_min_cpm allow_html5_ads allowed_ads apply_fade_on_midrolls as_launched_in_country baseUrl cafe_experiment_id cc_asr enabled_engage_types excluded_ads dynamic_allocation_ad_tag max_dynamic_allocation_ad_tag_length max_ad_duration ppv_remarketing_url prefetch_ad_live_stream pyv_ad_channel remarketing_url rmktEnabled show_pyv_in_related use_meta_ad_player".split(" "),
b=function(b){for(var a=h.length-1;0<=a;a--)if(b===h[a])return!0;return!1},f=d.getAttribute("flashvars"),w=d.cloneNode(!0);f=f.split("&");for(var m=[],l,q,ma=0;ma<f.length;ma++)l=f[ma].split("="),q=l[0],l=l[1],b(q)||m.push(q+"="+l);b=m.join("&");0>b.indexOf("enablejsapi")&&(b+="&enablejsapi=1");0>b.indexOf("iv_load_policy")&&(b+="&iv_load_policy=1");0>b.indexOf("autoplay")&&(b+="&autoplay=1");c.removeannotations&&(b=b.replace("iv_load_policy=1","iv_load_policy=3"));w.setAttribute("flashvars",b);p.textContent=
"";p.appendChild(w);Aa(p);H=!1;c.autopausevideos?ca():c.selectquality&&T()}else if(d){if(e||"function"===typeof d.getAdState&&1===d.getAdState()&&"function"===typeof d.getDuration){if(da)return;try{Number.isFinite(g.duration)?7<d.getDuration()-g.duration&&(da=!0,(w=d.querySelector("button.ytp-ad-skip-button"))?w.click():(g.currentTime=g.duration-.5,setTimeout(function(){var b=d.querySelector("button.ytp-ad-skip-button");b&&b.click()},2E3)),ea=0,D=!1,c.overridespeeds?g.playbackRate=n:d.setPlaybackRate(n),
c.autopausevideos&&ca()):setTimeout(function(){fa(e)},50)}catch(Oa){if(!g||(0<Oa.message.indexOf("currentTime")||"IndexSizeError"===Oa.message)&&g!=a.querySelector("video.html5-main-video"))return}}else Ba();0<=c.autofocusevents.indexOf("ads")&&t()}else setTimeout(function(){fa(e)},100)},Ba=function(){d.classList.add("ads-removed")},ha=function(){try{"object"===typeof U&&(U.disconnect(),U=void 0);var a=d.querySelector("button.ytp-settings-button"),h=d.querySelector("div.ytp-settings-menu");if(!H&&
a&&h){U=new MutationObserver(function(b){b.forEach(function(b){if(null!==b.addedNodes)for(var a=b.addedNodes.length-1;0<=a;a--)if("DIV"===b.addedNodes[a].nodeName&&b.addedNodes[a].classList.contains("ytp-menuitem")&&/\d{3,4}[p,s]/.test(b.addedNodes[a].textContent))b.addedNodes[a].click();else if("DIV"===b.addedNodes[a].nodeName&&b.addedNodes[a].classList.contains("ytp-quality-menu")){a=0;var e=!1,d={"4320p60 8K":"highres","4320p50 8K":"highres","4320p48 8K":"highres","4320p 8K":"highres","4320s 8K":"highres",
"2880p60 5K":"hd2880","2880p50 5K":"hd2880","2880p48 5K":"hd2880","2880p 5K":"hd2880","2880s 5K":"hd2880","2160p60 4K":"hd2160","2160p50 4K":"hd2160","2160p48 4K":"hd2160","2160p 4K":"hd2160","2160s 4K":"hd2160","1440p60 HD":"hd1440","1440p50 HD":"hd1440","1440p48 HD":"hd1440","1440p HD":"hd1440","1440s HD":"hd1440","1080p60 HD":"hd1080","1080p50 HD":"hd1080","1080p48 HD":"hd1080","1080p HD":"hd1080","1080s HD":"hd1080","720p60 HD":"hd720","720p50 HD":"hd720","720p48 HD":"hd720","720p HD":"hd720",
"720s HD":"hd720","480p":"large","480s":"large","360p":"medium","360s":"medium","240p":"small","240s":"small","144p":"tiny","144s":"tiny"},f=b.addedNodes[a].querySelectorAll("div.ytp-menuitem");0<f.length&&[c.quality1,c.quality2,c.quality3,c.quality4].forEach(function(b){if(!e){for(;a<f.length;a++)if(b===d[f[a].textContent]){f[a].click();e=!0;break}a=0}});e||f[0].click();H=!0;h.classList.remove("hidden");U.disconnect();t()}})});U.observe(h,{childList:!0,subtree:!0});for(var b=h.querySelectorAll("div.ytp-menuitem"),
f,g=b.length-1;0<=g;g--)if(/\d{3,4}[p,s]/.test(b[g].textContent)){f=b[g];break}h.classList.add("hidden");setTimeout(function(){h.classList.remove("hidden")},2500);f?(a.click(),f.click()):a.click()}else if(!H){var k=d.getAvailableQualityLevels();0<=k.indexOf(c.quality1)?d.setPlaybackQuality(c.quality1):0<=k.indexOf(c.quality2)?d.setPlaybackQuality(c.quality2):0<=k.indexOf(c.quality3)?d.setPlaybackQuality(c.quality3):0<=k.indexOf(c.quality4)&&d.setPlaybackQuality(c.quality4)}}catch(qb){}},G=function(e){if(!(a.body.classList.contains("no-scroll")||
A&&A.hasAttribute("fullscreen")||a.documentElement.hasAttribute("fullscreen")||a.documentElement.hasAttribute("hide-scrollbar"))){try{var h=a.body.classList.contains("enhancer-for-youtube-wide-player");A&&!V&&(V=A.hasAttribute("theater")&&!a.body.classList.contains("enhancer-for-youtube-wide-player"));if("large"===e||!e&&!h){Pa||Qa();var b=a.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]');b?b.parentNode.parentNode.click():A.setAttribute("theater-requested_",
"");a.body.classList.add("enhancer-for-youtube-wide-player");c.wideplayerviewport&&na&&(a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80)));!V&&setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:"0"})}))},
250)}else if("default"===e||!e&&h){if(!V){var f=a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');f?f.parentNode.parentNode.click():A.removeAttribute("theater-requested_");!f&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:"0"})}))}a.body.classList.remove("enhancer-for-youtube-wide-player","viewport","_viewport_");V=!1}}catch(w){}0<=c.autofocusevents.indexOf("size")&&
t();window.dispatchEvent(new Event("resize"))}},ca=function(){if(c.ignoreplaylists&&0<a.location.href.indexOf("list=")||!c.pauseforegroundtab&&!Z&&!a.hidden)c.selectquality&&(q?T():ha());else{clearInterval(S);try{c.disablepreloading?(d.stopVideo(),d.addEventListener("onStateChange",function w(a){if(1===a){d.removeEventListener("onStateChange",w);c.selectquality&&q&&T();try{d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",c.removeannotations?
0:1),"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&ytplayer.config.args.start&&d.seekTo(parseInt(ytplayer.config.args.start,10))}catch(m){}}})):d.pauseVideo()}catch(b){var e,h=0;S=setInterval(function(){try{d&&"function"===typeof d.getPlayerState||(h++,"video"===F?O():za()),e=d.getPlayerState(),a.hidden?-1!==e&&c.disablepreloading?d.stopVideo():2===e||c.disablepreloading||d.pauseVideo():-1!==e&&5!==e&&c.pauseforegroundtab&&c.disablepreloading?d.stopVideo():2!==e&&c.pauseforegroundtab&&
!c.disablepreloading?(-1!==e&&5!==e||d.playVideo(),3!==e&&d.pauseVideo()):clearInterval(S)}catch(f){200<h&&clearInterval(S),d=!1}},50)}t()}},Ra=function(a){if(a.ctrlKey&&!a.shiftKey&&"function"===typeof d.getPlayerState&&0<d.getPlayerState()||"I"===a.target.nodeName){a.preventDefault();n=c.speed;try{c.overridespeeds?g.playbackRate=n:d.setPlaybackRate(n),"I"===a.target.nodeName&&c.toolbartooltips?v.textContent=z.speed+" x"+n:(M.textContent="x"+n,Ca())}catch(h){}0<=c.autofocusevents.indexOf("speed")&&
t()}},Ca=function(){M.setAttribute("style","display:block!important");clearTimeout(Sa);Sa=setTimeout(function(){M.setAttribute("style","display:none!important")},1500)},Ja=function(){x.style.marginLeft="-"+k.getBoundingClientRect().width/2+"px"},I=function(a,h){a.addEventListener("mouseenter",function(b){c.toolbartooltips&&(v.textContent=h,v.style.left=b.target.getBoundingClientRect().left+b.target.clientWidth/2-v.clientWidth/2+"px",v.classList.add("visible"))});a.addEventListener("mouseleave",function(){v.classList.remove("visible")})},
Ta=function(){try{B.max=g.duration,B.value=g.currentTime}catch(e){}},oa=function(a){a.preventDefault();if(!q){try{if(c.overridespeeds){var e=g.playbackRate;if(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)e=parseFloat((e-c.speedvariation).toFixed(2)),0>=e&&(e=c.speedvariation),g.playbackRate=e;else if(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)e=parseFloat((e+c.speedvariation).toFixed(2)),g.playbackRate=e}else{var b=d.getAvailablePlaybackRates();
e=d.getPlaybackRate();var f=b.indexOf(e);(!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY)&&0<f?(e=b[f-1],d.setPlaybackRate(e)):(!c.reversemousewheeldirection&&0>a.deltaY||c.reversemousewheeldirection&&0<a.deltaY)&&f<b.length-1&&(e=b[f+1],d.setPlaybackRate(e))}n=e;"I"===a.target.nodeName&&c.toolbartooltips?v.textContent=z.speed+" x"+e:(M.textContent="x"+e,Ca())}catch(w){}0<=c.autofocusevents.indexOf("speed")&&t()}},fb=function(a){if(a.ctrlKey)oa(a);else if(c.controlvolume&&
(c.controlvolumemousebutton&&la||!c.controlvolumemousebutton)){a.preventDefault();try{var e=d.getVolume();!c.reversemousewheeldirection&&0<a.deltaY||c.reversemousewheeldirection&&0>a.deltaY?(e-=c.volumevariation,0>e&&(e=0)):(e+=c.volumevariation,100<e&&(e=100),d.isMuted()&&d.unMute());ka=!0;d.setVolume(e);M.textContent=e;Ca();c.defaultvolume&&(c.volume=e);var b=Date.now();a=0<e?"false":"true";localStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","expiration":'+(b+2592E6)+
',"creation":'+b+"}";sessionStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+e+',\\"muted\\":'+a+'}","creation":'+b+"}"}catch(f){}}},gb=function(a){a.shiftKey?Ua(a):a.ctrlKey&&Ra(a)},Ua=function(a){if("I"===a.target.nodeName||a.ctrlKey&&a.shiftKey){a.preventDefault();try{var e=""===(g.style.filter?g.style.filter:g.style["-webkit-filter"])?!1:!0;g.style["-webkit-filter"]=e?"":c.filter;g.style.filter=e?"":c.filter;k.querySelector("i.filters").parentNode.classList[e?"remove":"add"]("active")}catch(b){}0<=
c.autofocusevents.indexOf("filters")&&t()}},Aa=function(c){c.querySelector("#enhancer-for-youtube-player-info")||(a.querySelector("#enhancer-for-youtube-player-info")||(M=a.createElement("div"),M.id="enhancer-for-youtube-player-info"),c.appendChild(M))},Va=function(c){var e=a.location.href.match(/&?v=([^&\?]+)/)[1]+"?autoplay=1",b=a.location.href.match(/&?list=([^&\?]+)/);b&&(e+="&list="+b[1]);try{d.pauseVideo();var f=d.getCurrentTime();f&&(e+="&start="+parseInt(f,10));c&&d.stopVideo()}catch(w){}a.dispatchEvent(new CustomEvent("efyt-message",
{detail:JSON.stringify({enhancerforyoutube:"detach",params:e})}))},Da=function(a){if(c.toolbartooltips){var e="";try{e=" x"+g.playbackRate}catch(b){}v.textContent=z.speed+e;v.style.left=a.target.getBoundingClientRect().left+a.target.clientWidth/2-v.clientWidth/2+"px";v.classList.add("visible")}},hb=function(){if(!x){y=a.createElement("div");x=a.createElement("div");k=a.createElement("div");v=a.createElement("div");var e=a.createDocumentFragment(),h=a.createElement("ul"),b=a.createElement("li"),f=
a.createElement("i");y.id="enhancer-for-youtube-background";y.style.visibility="hidden";y.addEventListener("click",function(){ia()});e.appendChild(y);x.id="enhancer-for-youtube-toolbar-wrapper";k.id="enhancer-for-youtube-toolbar";v.id="enhancer-for-youtube-tooltip";e.appendChild(v);k.style.visibility="hidden";c.transparency&&k.classList.add("transparency");c.slideeffect&&k.classList.add("slide-effect");b.dataset.name=f.className="message";b.appendChild(f);f=a.createElement("i");f.className="badge";
b.appendChild(f);b.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-message"})}))});I(b,z.message);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="clean";b.appendChild(f);b.addEventListener("click",function(){pa=!0;da=!1;fa()});b.addEventListener("contextmenu",function(a){a.preventDefault();d||O();try{var b=d.getAttribute("annotations-module-loaded");d["1"===b?"unloadModule":
"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded","1"===b?0:1);0<=c.autofocusevents.indexOf("annotations")&&t()}catch(sb){}return!1});I(b,z.remove_ads);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="cinema";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-cinema-mode")?ia():ya()});I(b,z.cinema_mode);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=
f.className="resize";b.appendChild(f);b.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-pinned-player")||(a.body.classList.contains("enhancer-for-youtube-pinned-player")&&(a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.scrollTo(0,0)),G())});b.addEventListener("contextmenu",function(b){b.preventDefault();b=a.querySelector("ytd-masthead");try{window.scrollTo(window.scrollX,p.getBoundingClientRect().top-
(a.body.classList.contains("viewport")?0:b?b.clientHeight:56)+window.scrollY)}catch(rb){}return!1});I(b,z.resize_player);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="detach";b.appendChild(f);b.addEventListener("click",function(){Va(!1)});b.addEventListener("contextmenu",function(a){a.preventDefault();Va(!0);return!1});I(b,z.detach_player);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="boost";b.appendChild(f);
b.addEventListener("click",function(){if(g){if(!W){var a=new (window.AudioContext||window.webkitAudioContext),b=a.createMediaElementSource(g);W=a.createGain();b.connect(W);W.connect(a.destination)}this.classList.contains("active")?(W.gain.value=1,this.classList.remove("active")):(W.gain.value=3,this.classList.add("active"));0<=c.autofocusevents.indexOf("boost")&&t()}});I(b,z.boost_volume);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="loop";b.appendChild(f);
b.addEventListener("click",function(){if(Wa)La(this);else{Wa=!0;l=a.createElement("link");l.rel="stylesheet";l.href=P+"/vendor/jquery/jquery-ui.min.css";a.head.appendChild(l);var b=this,e=a.createElement("script");e.src=P+"/vendor/jquery/jquery-3.3.1.min.js";e.onload=function(){e=a.createElement("script");e.src=P+"/vendor/jquery/jquery-ui.min.js";e.onload=function(){La(b)};a.head.appendChild(e)};a.head.appendChild(e)}0<=c.autofocusevents.indexOf("loop")&&t()});I(b,z.loop_video);h.appendChild(b);b=
a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="slowdown";b.appendChild(f);f=a.createElement("i");f.className="minus";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",function(){oa({target:{nodeName:"I"},deltaY:1,preventDefault:function(){}})});b.addEventListener("mouseenter",Da);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className=
"speed";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",Ra);b.addEventListener("wheel",oa);b.addEventListener("mouseenter",Da);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="speedup";b.appendChild(f);f=a.createElement("i");f.className="plus";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",function(){oa({target:{nodeName:"I"},
deltaY:-1,preventDefault:function(){}})});b.addEventListener("mouseenter",Da);b.addEventListener("mouseleave",function(){v.classList.remove("visible")});h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="filters";b.appendChild(f);q&&b.classList.add("not-allowed");b.addEventListener("click",Ua);b.addEventListener("touchstart",function(b){if(this.hasAttribute("ui"))a.querySelector("#enhancer-for-youtube-filters").classList[this.classList.contains("active")?"add":
"remove"]("hidden");else a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})}))});b.addEventListener("contextmenu",function(b){b.preventDefault();this.classList.contains("not-allowed")||(this.hasAttribute("ui")?a.querySelector("#enhancer-for-youtube-filters").classList.toggle("hidden"):a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"filters"})})));return!1});I(b,z.filters);h.appendChild(b);b=a.createElement("li");
f=a.createElement("i");b.dataset.name=f.className="script";b.appendChild(f);b.addEventListener("click",function(){t();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}))});I(b,z.custom_script);h.appendChild(b);b=a.createElement("li");f=a.createElement("i");b.dataset.name=f.className="options";b.appendChild(f);b.addEventListener("click",function(){t();a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"show-options"})}))});
I(b,z.options);h.appendChild(b);k.appendChild(h);x.appendChild(k);e.appendChild(x);B=a.createElement("progress");B.id="enhancer-for-youtube-progress";B.max=1;B.value=0;B.addEventListener("click",function(a){g&&(g.currentTime=Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth));t()});B.addEventListener("mouseenter",function(){N.classList.add("visible")});B.addEventListener("mouseleave",function(){N.classList.remove("visible")});B.addEventListener("mousemove",function(a){g&&(N.textContent=
xa(Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth)),N.style.left=a.pageX-N.getBoundingClientRect().width/2+"px")});e.appendChild(B);N=a.createElement("div");N.id="enhancer-for-youtube-progress-tooltip";e.appendChild(N);h=a.createElement("div");h.id="enhancer-for-youtube-unpin-player";h.addEventListener("click",function(){a.body.classList.remove("enhancer-for-youtube-pinned-player")});e.appendChild(h);a.body.appendChild(e);setTimeout(function(){va();Ja();y.style.visibility="";k.style.visibility=
""},500);if((e=d.querySelector(".ytp-right-controls"))&&!e.querySelector(".efy-ytp-keyboard-shortcuts")){var w,m=a.createElement("div");h=a.createElement("div");b=a.createElement("span");var n=a.createElement("button");f=a.createElementNS("http://www.w3.org/2000/svg","svg");var r=a.createElementNS("http://www.w3.org/2000/svg","path"),u=e.querySelector('button:not([style*="display"])');b.className="ytp-tooltip-text";b.textContent=z.keyboard_shortcuts+" \ud83d\uddd7";h.appendChild(b);h.className="ytp-tooltip-text-wrapper";
m.appendChild(h);m.className="ytp-bottom";m.style.display="none";d.appendChild(m);n.className="ytp-button efy-ytp-keyboard-shortcuts";n.addEventListener("click",function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"keyboard-shortcuts"})}))});n.addEventListener("mouseenter",function(a){u.dispatchEvent(new Event("mouseover"));u.dispatchEvent(new Event("mouseout"));w||(w=d.querySelector(".ytp-tooltip"));w&&""!==w.style.top&&(m.classList.add("ytp-tooltip"),
m.style.display="block",m.style.top=w.style.top,m.style.left=n.offsetLeft+a.target.getBoundingClientRect().width-m.getBoundingClientRect().width/2+"px")});n.addEventListener("mouseleave",function(){m.style.display="none";m.classList.remove("ytp-tooltip")});f.setAttributeNS(null,"version","1.1");f.setAttributeNS(null,"viewBox","0 0 36 36");f.setAttributeNS(null,"height","100%");f.setAttributeNS(null,"width","100%");r.setAttributeNS(null,"d","m26 11h-16c-1.1 0-1.99.9-1.99 2l-.01 10c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2v-10c0-1.1-.9-2-2-2zm-9 3h2v2h-2zm0 3h2v2h-2zm-3-3h2v2h-2zm0 3h2v2h-2zm-1 2h-2v-2h2zm0-3h-2v-2h2zm9 7h-8v-2h8zm0-4h-2v-2h2zm0-3h-2v-2h2zm3 3h-2v-2h2zm0-3h-2v-2h2z");
r.setAttributeNS(null,"fill","#fff");n.appendChild(f);f.appendChild(r);e.insertBefore(n,e.firstChild)}}},Qa=function(){var c=a.documentElement.clientWidth,d=a.documentElement.clientHeight;if(c!==Xa||d!==Ya){Xa=c;Ya=d;var b=window.innerWidth,f=a.querySelector("ytd-masthead");f=f?f.getBoundingClientRect().height:56;var g=k?k.getBoundingClientRect().height:29;if(parseInt(16/9*(d-f-g),10)>c){f=c;g=parseInt(f/(16/9),10);d=f;var m=g;na=!1}else g=parseInt(d-f-g,10),f=parseInt(16/9*g,10),b-=b-f,m=window.screen.height===
d?d-12:d,d=parseInt(16/9*m,10),na=!0;var p=parseInt(b/(16/9),10);var l=parseInt((c-f)/2,10);c=parseInt((c-d)/2,10);var n=a.createElement("style");n.type="text/css";n.textContent="body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
g+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
m+"px !important}body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+f+"px !important;left:"+l+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+
d+"px !important;left:"+c+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) #player-theater-container,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater]:not([fullscreen]) embed#movie_player,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
p+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch-flexy[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+b+"px !important}";a.head.appendChild(n);Pa=!0}},Za=function(){window.IntersectionObserver&&!p.hasAttribute("io")&&(p.setAttribute("io",1),Ea=new IntersectionObserver(function(e){if((0===
e[0].intersectionRatio&&!a.body.classList.contains("enhancer-for-youtube-pinned-player")&&0<window.scrollY||0<e[0].intersectionRatio&&.12>e[0].intersectionRatio)&&window.scrollY>p.offsetHeight-100&&Q()){if(!d||!d.classList.contains("ended-mode")){g&&g.addEventListener("timeupdate",Ta);a.body.classList.add("enhancer-for-youtube-pinned-player");try{g.style.top=""}catch(h){}0<=c.autofocusevents.indexOf("pin")&&t()}}else 0!==e[0].intersectionRatio&&(g&&g.removeEventListener("timeupdate",Ta),a.body.classList.remove("enhancer-for-youtube-pinned-player"),
window.dispatchEvent(new Event("resize")),q||ib())},{threshold:.12}),Ea.observe(p))},ib=function(){setTimeout(function(){try{if(!a.body.classList.contains("enhancer-for-youtube-pinned-player")){var c=p.clientHeight,h=g.clientHeight;d.clientHeight!==c?(d.style.width=p.clientWidth,d.style.height=c,d.style.width="",d.style.height=""):h!==c&&(g.style.width=p.clientWidth,g.style.height=c,g.style.top="")}}catch(b){}},50)},$a=function(){(new MutationObserver(function(e){e.forEach(function(e){try{a.hidden||
!a.body.classList.contains("enhancer-for-youtube-wide-player")||e.target.hasAttribute("theater-requested_")||e.target.hasAttribute("theater")||(a.body.classList.remove("enhancer-for-youtube-wide-player"),V=!1,setTimeout(function(){a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:c.theatermode?"1":"0"})}))},250))}catch(b){}})})).observe(A,{attributes:!0})},jb=function(){sa=setInterval(function(){try{if("function"!==
typeof d.getPlayerState&&O(),0===d.getPlayerState()&&(clearInterval(sa),!k.querySelector("i.loop").parentNode.classList.contains("active"))){var c=a.querySelector("ytd-watch-flexy ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]");if(c){var h=c.nextElementSibling;h&&(a.location.href=h.querySelector("a").href)}}}catch(b){}},5E3)},Fa=function(){var e=c.backgroundcolor.replace("#",""),d=parseInt(e.substring(0,2),16),b=parseInt(e.substring(2,4),16);e=parseInt(e.substring(4,6),16);
l=a.createElement("style");l.type="text/css";l.textContent="body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player .html5-video-player{background-color:rgba("+d+","+b+","+e+","+c.backgroundopacity/100+")}";a.head.appendChild(l)},t=function(){try{a.activeElement.blur(),d.focus({preventScroll:!0})}catch(e){}},za=function(){d=a.querySelector("#c4-player")},O=function(){d=a.querySelector("#movie_player")},Q=function(){return/^https:\/\/www\.youtube\.com\/watch\?(.*&)?v=/.test(a.location.href)||
/^https:\/\/www\.youtube\.com\/.*\/live/.test(a.location.href)},qa=function(a,c){var b=parseInt(a.slice(1),16),e=0>c?0:255,d=0>c?-1*c:c,g=b>>16,h=b>>8&255;b&=255;return"#"+(16777216+65536*(Math.round((e-g)*d)+g)+256*(Math.round((e-h)*d)+h)+(Math.round((e-b)*d)+b)).toString(16).slice(1)},ab=function(){var d=a.createElement("style"),g=c.toolbarbackgroundcolor.replace("#",""),b=parseInt(g.substring(0,2),16),f=parseInt(g.substring(2,4),16);g=parseInt(g.substring(4,6),16);d.type="text/css";d.textContent=
"#enhancer-for-youtube-toolbar,body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-toolbar-wrapper:hover #enhancer-for-youtube-toolbar{background-color:"+c.toolbarbackgroundcolor+";border-top:1px solid "+c.toolbarbordercolor+";border-right:1px solid "+c.toolbarbordercolor+";border-left:1px solid "+c.toolbarbordercolor+";color:"+c.toolbarcolor+"}#enhancer-for-youtube-toolbar i{color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-toolbar li.active i{color:"+c.toolbarcoloractive+" !important}#enhancer-for-youtube-toolbar.transparency{opacity:"+
c.toolbaropacity/100+"}#enhancer-for-youtube-slider.ui-widget-content{background-image:none;background-color:"+c.toolbarbackgroundcolor+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-widget-header{background-image:none;background-color:"+qa(c.toolbarbackgroundcolor,-.1)+"}#enhancer-for-youtube-slider .ui-state-default{background-image:none;background-color:"+qa(c.toolbarbackgroundcolor,-.1)+";border:1px solid "+c.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-state-hover,#enhancer-for-youtube-slider .ui-state-focus{background-image:none;background-color:"+
qa(c.toolbarbackgroundcolor,-.15)+";border:1px solid "+qa(c.toolbarbordercolor,-.15)+"}#enhancer-for-youtube-toolbar .start-end{background-color:rgba("+b+","+f+","+g+",0.85)}#enhancer-for-youtube-filters{background-color:"+c.toolbarbackgroundcolor+" !important;border:1px solid "+c.toolbarbordercolor+" !important;color:"+c.toolbarcolor+" !important}#enhancer-for-youtube-unpin-player,#enhancer-for-youtube-filters button.close{color:"+c.toolbarcolor+" !important}";a.head.appendChild(d)},kb=function(){bb=
setInterval(function(){try{(a.activeElement.classList.contains("ytp-progress-bar")||a.activeElement.classList.contains("ytp-volume-panel"))&&t()}catch(e){}},3E3)},lb=function(){clearInterval(bb);la=ka=!1},mb=function(a){try{100<=a&&setTimeout(function(){d.nextVideo()},2E3)}catch(h){}},cb=function(a){1===a&&(d.removeEventListener("onStateChange",cb),g&&c.overridespeeds?g.playbackRate=n:d.setPlaybackRate(n))},nb=function(a){"number"===typeof a&&(n=a)},ob=function(e){try{c.pausevideos&&L&&1===e&&!D&&
(D=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})}))),c.autopausevideos&&!L&&1===e&&ca(),c.selectquality&&!H&&1===e&&ha(),2===e&&(D=!1),0===e&&"video"===F&&(D=!1,setTimeout(function(){d.classList.contains("ended-mode")&&(B.value=B.max)},500))}catch(h){}},pb=function(e){try{c.pausevideos&&L&&1===e&&!D&&(D=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})})));(c.removeads&&1===
e||pa&&1===e)&&ea++;if(c.removeads&&1===e&&3>ea&&0>ra.indexOf(C)||pa&&1===e&&3>ea)"video"===F?fa(e):(g.currentTime=g.duration-.5,Ba());2===e&&(D=!1);0===e&&(da=D=!1,d.addEventListener("onStateChange",cb))}catch(h){}},X=function(){l||(l=a.createElement("link"),l.rel="stylesheet",l.href=P+"/youtube-polymer.css",a.head.appendChild(l),l=a.createElement("style"),l.type="text/css",l.textContent="#enhancer-for-youtube-background{background-color:"+c.backgroundcolor+"}body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-background{opacity:"+
c.backgroundopacity/100+";visibility:visible}",a.head.appendChild(l),Fa(),ab());F=d=p=g=pa=da=H=!1;ea=0;if(Q())if(F="video",O(),d)try{C=d.getVideoData().author}catch(e){(C=a.querySelector("#owner-name.ytd-video-owner-renderer"))&&(C=C.textContent.trim())}else C="";else if(/^https:\/\/www\.youtube\.com\/channel\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/channel\/[^\/]+\/featured/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+\/featured/.test(a.location.href))if(F=
"channel",za(),d)try{C=d.getVideoData().author}catch(e){(C=a.querySelector("h1 #channel-title"))&&(C=C.textContent.trim())}else C="";if(F&&d){p=d.parentNode;"EMBED"===d.nodeName?(q=!0,"video"===F&&0<a.location.href.indexOf("list=")&&jb(),a.body.classList.add("flash-player-loaded")):(g=d.querySelector("video.html5-main-video"),d.addEventListener("onAdStateChange",pb),d.addEventListener("onStateChange",ob),d.addEventListener("onPlaybackRateChange",nb),d.addEventListener("onError",mb),p.addEventListener("mouseleave",
lb),p.addEventListener("mouseenter",kb),p.addEventListener("wheel",fb),p.addEventListener("click",gb),setTimeout(function(){try{g&&c.overridespeeds?(g.playbackRate=n,g.defaultPlaybackRate=n):d.setPlaybackRate(n)}catch(e){}},500));"video"===F?(c.removeads&&0>ra.indexOf(C)&&(q||!q&&1===d.getAdState())?fa():c.autopausevideos&&(q||!q&&1===d.getPlayerState())?ca():c.selectquality&&(q?T():ha()),(c.removeads&&0>ra.indexOf(C)||c.removeads&&c.permissions)&&Ba(),c.cinemamode?setTimeout(function(){ya();!c.cinemamodewideplayer&&
c.wideplayer&&G("large")},c.cinemamodewideplayer||c.wideplayer?1200:1):c.wideplayer&&setTimeout(function(){G("large")},1200),x?(x.style.display="",y.style.display=""):hb(),!c.pausevideos||Z||D||(D=!0,a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"pause-videos"})}))),c.pinnedplayer&&(Za(),a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition)),c.expanddescription&&setTimeout(function(){var c=a.querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#more");
try{c.click()}catch(h){}},2E3),c.disableautoplay&&!ta&&ua(),0<a.location.href.indexOf("list=")&&setTimeout(function(){try{var c=a.querySelector("ytd-playability-error-supported-renderers");c&&240<=c.getBoundingClientRect().height&&a.querySelector("ytd-watch-flexy ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]").nextElementSibling.querySelector("a").click()}catch(h){}},2E3)):"channel"===F&&(c.autopausevideos?ca():c.selectquality&&(q?T():ha()));Aa(q?p:d);c.controlvolume&&g&&
(p.addEventListener("mousedown",Na),g.addEventListener("contextmenu",Ma));c.enablefilters&&g&&(g.style["-webkit-filter"]=c.filter,g.style.filter=c.filter);try{c.defaultvolume&&d.setVolume(c.volume),d[c.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",c.removeannotations?0:1)}catch(e){}}};window.EnhancerForYouTube=!0;var P=EnhancerForYouTubeResources,c=EnhancerForYouTubePreferences,z=EnhancerForYouTubeMessages,A=a.querySelector("ytd-watch-flexy"),
p,d,g,y,x,k,v,M,Sa,E,Ka,B,N,W,Z=a.hidden,L=!a.hidden,ta,ka,la,D,Ea,Wa,q,Pa,na,Xa,Ya,F,S,bb,sa,ba,db,J,r,u,V,pa,ea=0,da,H,C,ra=""!==c.whitelist?c.whitelist.split(","):[],n=c.speed,aa,U;(new MutationObserver(function(e){e.forEach(function(e){if(null!==e.addedNodes)for(var b=e.addedNodes.length-1;0<=b;b--)if(q||!e.addedNodes[b].id||"movie_player"!==e.addedNodes[b].id&&"c4-player"!==e.addedNodes[b].id)if("YTD-WATCH-FLEXY"===e.addedNodes[b].nodeName)A=e.addedNodes[b],$a();else if("VIDEO"===e.addedNodes[b].nodeName&&
g&&g!=d.querySelector("video.html5-main-video"))g=e.addedNodes[b],setTimeout(function(){L=!1;X();try{g&&c.overridespeeds?(g.playbackRate=n,g.defaultPlaybackRate=n):d.setPlaybackRate(n)}catch(f){}},650);else if("YTD-VIDEO-SECONDARY-INFO-RENDERER"===e.addedNodes[b].nodeName&&c.expanddescription)try{e.addedNodes[b].querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#more").click()}catch(f){}else"YT-SORT-FILTER-SUB-MENU-RENDERER"===e.addedNodes[b].nodeName&&c.newestcomments?
setTimeout(function(){try{a.querySelector("ytd-comments yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type").click(),aa=!0}catch(f){}},500):"YTD-COMMENT-THREAD-RENDERER"===e.addedNodes[b].nodeName&&c.newestcomments&&!aa&&20===e.addedNodes[b].parentNode.children.length?setTimeout(function(){try{!aa&&a.querySelector("ytd-comments yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type").click(),aa=!0}catch(f){}},4E3):c.disableautoplay&&!ta&&"YTD-COMPACT-AUTOPLAY-RENDERER"===e.addedNodes[b].nodeName&&
ua(e.addedNodes[b]);else if("EMBED"===e.addedNodes[b].nodeName){try{d.stopVideo()}catch(f){}p=e.addedNodes[b].parentNode;Aa(p);k&&(k.querySelector(".speed").classList.add("not-allowed"),k.querySelector(".filters").classList.add("not-allowed"));"complete"===a.readyState&&X()}})})).observe(a.body,{childList:!0,subtree:!0});A&&$a();window.addEventListener("yt-history-load",Ha);window.addEventListener("yt-navigate-start",Ha);window.addEventListener("yt-navigate-finish",function(c){a.hidden||setTimeout(function(){L=
!0;Z=!1},1500);X()});(a.querySelector("video.html5-main-video")||a.querySelector("#movie_player")||a.querySelector("#c4-player"))&&X();a.addEventListener("visibilitychange",function h(){a.hidden||(L||X(),a.removeEventListener("visibilitychange",h),setTimeout(function(){L=!0;Z=!1},1500))});window.addEventListener("load",function b(){window.removeEventListener("load",b);setTimeout(function(){l||X()},250)});c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));
c.theme=c.theme.replace(".css","-polymer.css");if("default"!==c.theme){var K=a.head.querySelector("#enhancer-for-youtube-theme");K?K.hasAttribute("href")&&0>K.href.indexOf(c.theme)&&K.setAttribute("href",P+"/vendor/themes/"+c.theme):"custom"===c.theme?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):(K=a.createElement("link"),K.id="enhancer-for-youtube-theme",K.rel="stylesheet",K.href=P+"/vendor/themes/"+c.theme,a.head.appendChild(K))}a.addEventListener("efyt-pause-video",
function(a){try{d.pauseVideo()}catch(f){}});a.addEventListener("efyt-preference-changed",function(b){var f=JSON.parse(b.detail);b=f.value;switch(f.name){case "autofocusevents":case "autopausevideos":case "controlvolumemousebutton":case "disableautoplay":case "disablepreloading":case "ignoreplaylists":case "newestcomments":case "overridespeeds":case "pauseforegroundtab":case "pausevideos":case "permissions":case "removeads":case "reversemousewheeldirection":case "speedvariation":case "toolbartooltips":case "volumevariation":c[f.name]=
b;break;case "backgroundcolor":c.backgroundcolor=b;y&&(y.style.backgroundColor=b);Fa();break;case "backgroundopacity":c.backgroundopacity=b;y&&(y.style.opacity=b/100);Fa();break;case "cinemamode":c.cinemamode=b;Q()&&(b?ya():ia());break;case "cinemamodewideplayer":c.cinemamodewideplayer=b;Q()&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(b?G("large"):G("default"));break;case "controlvolume":c.controlvolume=b;if(p)p[b?"addEventListener":"removeEventListener"]("mousedown",Na);if(g)g[b?
"addEventListener":"removeEventListener"]("contextmenu",Ma);break;case "customtheme":if("default"!==c.theme)try{a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme"))}catch(m){}var l=a.createElement("style");l.type="text/css";l.id="enhancer-for-youtube-theme";l.textContent=b;a.head.appendChild(l);Ia(b);break;case "defaultvolume":c.defaultvolume=b;try{b&&d.setVolume(c.volume)}catch(m){}break;case "enablefilters":c.enablefilters=b;try{g.style["-webkit-filter"]=b?c.filter:"",g.style.filter=
b?c.filter:""}catch(m){}break;case "executescript":c.executescript=b;c.executescript&&a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-script"})}));break;case "expanddescription":c.expanddescription=b;try{a.querySelector("ytd-video-secondary-info-renderer.ytd-watch-flexy paper-button#"+(b?"more":"less")).click()}catch(m){}break;case "filter":c.filter=b;if(!a.hidden)try{g.style["-webkit-filter"]=b,g.style.filter=b,k.querySelector("i.filters").parentNode.classList.add("active")}catch(m){}break;
case "message":c.message=b;va();break;case "pinnedplayer":c.pinnedplayer=b;p&&p.removeAttribute("io");if(b)a.body.classList.add(c.pinnedplayersize,c.pinnedplayerposition),Q()&&Za();else try{a.body.classList.remove("enhancer-for-youtube-pinned-player",c.pinnedplayersize,c.pinnedplayerposition),Ea.disconnect()}catch(m){}break;case "pinnedplayerposition":a.body.classList.add(b);a.body.classList.remove(c.pinnedplayerposition);c.pinnedplayerposition=b;break;case "pinnedplayersize":a.body.classList.add(b);
a.body.classList.remove(c.pinnedplayersize);c.pinnedplayersize=b;break;case "quality1":case "quality2":case "quality3":case "quality4":case "selectquality":c[f.name]=b;if("quality1"===f.name||c.selectquality)b=Date.now(),localStorage["yt-player-quality"]='{"data":"'+c.quality1+'","expiration":'+(b+2592E6)+',"creation":'+b+"}";F&&c.selectquality&&(H=!1,q?T():ha());break;case "removeannotations":c.removeannotations=b;try{d[b?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",
b?0:1)}catch(m){}break;case "slideeffect":c.slideeffect=b;if(k)k.classList[b?"add":"remove"]("slide-effect");break;case "speed":c.speed=n=b;try{0>[.25,.5,1,1.25,1.5,1.75,2].indexOf(b)?(g.playbackRate=b,g.defaultPlaybackRate=b):d.setPlaybackRate(b)}catch(m){}break;case "theatermode":c.theatermode=b;if(Q())try{b?d.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]').parentNode.parentNode.click():d.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]').parentNode.parentNode.click()}catch(m){}break;
case "theme":try{"default"!==c.theme&&a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme")),c.theme=b.replace(".css","-polymer.css"),"custom"===b?a.dispatchEvent(new CustomEvent("efyt-message",{detail:JSON.stringify({enhancerforyoutube:"custom-theme"})})):"default"!==b&&(l=a.createElement("link"),l.id="enhancer-for-youtube-theme",l.rel="stylesheet",l.href=P+"/vendor/themes/"+c.theme,a.head.appendChild(l))}catch(m){}Ia();break;case "toolbarbuttons":c.toolbarbuttons=b;k&&va();break;
case "toolbarbackgroundcolor":case "toolbarbordercolor":case "toolbarcolor":case "toolbarcoloractive":case "toolbaropacity":c[f.name]=b;ab();break;case "transparency":c.transparency=b;if(k)k.classList[b?"add":"remove"]("transparency");break;case "volume":c.volume=b;try{d.setVolume(b)}catch(m){}break;case "whitelist":ra=""!==b?b.split(","):[];break;case "wideplayer":c.wideplayer=b;Q()&&(b?G("large"):G("default"));break;case "wideplayerviewport":(c.wideplayerviewport=b,b)?b&&na&&(a.body.classList.contains("enhancer-for-youtube-wide-player")&&
a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80))):a.body.classList.remove("viewport","_viewport_")}});window.addEventListener("error",function(b){setTimeout(function(){q||!d||d.querySelector("video")||a.location.reload()},a.documentElement.hasAttribute("flash-player-for-youtube")||
a.documentElement.hasAttribute("youtube-flash-player")?3E3:1)});window.addEventListener("resize",function(a){clearTimeout(db);db=setTimeout(Qa,500)});a.addEventListener("keydown",function(a){27===a.keyCode&&d&&!d.classList.contains("ytp-fullscreen")&&y&&y.click()});var Ga="fullscreenchange";"onwebkitfullscreenchange"in a?Ga="webkitfullscreenchange":"onmozfullscreenchange"in a&&(Ga="mozfullscreenchange");a.addEventListener(Ga,function(b){setTimeout(function(){d&&!d.classList.contains("ytp-fullscreen")&&
a.body.classList.contains("enhancer-for-youtube-wide-player")&&window.dispatchEvent(new Event("resize"))},500)})}else if(EnhancerForYouTubePreferences.message){var l=a.createElement("link");l.rel="stylesheet";l.href=EnhancerForYouTubeResources+"/youtube-polymer.css";a.head.appendChild(l);var Y=a.createElement("div"),R=a.createElement("i");Y.id="page-reload-required";Y.textContent=EnhancerForYouTubeMessages.page_reload_required;R.className="refresh";R.addEventListener("click",function(){a.location.reload()});
Y.appendChild(R);R=a.createElement("i");R.className="close";R.addEventListener("click",function(){Y.style.display="none"});Y.appendChild(R);a.body.appendChild(Y)}})(document);