# Generated by Django 2.2.1 on 2019-05-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
